nginx:
  build: "nginx"
  restart: always
  ports:
    - "443:443"
  links:
    - registry:registry

registry:
  image: registry:2
  restart: always
  environment:
    - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/var/lib/registry
  ports:
    - "5000:5000"
  volumes:
    - /var/opt/registry:/var/lib/registry

frontend:
  image: konradkleine/docker-registry-frontend:v2
  restart: always
  environment:
    - ENV_DOCKER_REGISTRY_HOST=registry
    - ENV_DOCKER_REGISTRY_PORT=5000
  ports:
    - "80:80"
  links:
    - registry:registry

